In [50]:
import numpy as np

### INTRO TO NUMPY
#### Arrays

In [51]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [52]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [54]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [55]:
a = np.array([1, 2, 3, 5, 12])
a

array([ 1,  2,  3,  5, 12])

In [56]:
a[2]

3

In [57]:
#TO change item to a diff number
a[2] = 10
a

array([ 1,  2, 10,  5, 12])

In [58]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [60]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### Multidimensional Arrays

In [61]:
# Create an array of zeros, with 5 columns and 2 rows
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [62]:
# Create an array off python lists (list of lists)
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
# To access elements of the above array
n[0, 1]

2

In [64]:
n[0, 1] =20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [65]:
# TO get the rows only
n[0]

array([ 1, 20,  3])

In [66]:
n[2] = [1, 1, 1]
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [67]:
# TO get all the elements of a particular column
n[:, 1]

array([20,  5,  1])

In [68]:
# To return all rows
n[:]

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 1,  1,  1]])

In [69]:
n[:, 2]

array([3, 6, 1])

In [70]:
n[:, 2] = [0, 1, 2]
n

array([[ 1, 20,  0],
       [ 4,  5,  1],
       [ 1,  1,  2]])

### Randomly generated arrays

In [71]:
# Randomly generated array of 5 rows and 2 columns

# If we use seed, it makes sure the randomly generated numbers remain the same every time
# np.random.seed(2)

np.random.rand(5, 2)

array([[0.20464863, 0.61927097],
       [0.29965467, 0.26682728],
       [0.62113383, 0.52914209],
       [0.13457995, 0.51357812],
       [0.18443987, 0.78533515]])

In [72]:
# To get a random normal distribution
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [73]:
# To get numbers between 0-100
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [74]:
# To generate random integers indicating the highest and lowest intervals
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise Operations

In [75]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [76]:
# To add 1 to the array, rather than making use of a for loop
a + 1

array([1, 2, 3, 4, 5])

In [77]:
a * 2

array([0, 2, 4, 6, 8])

In [78]:
# Chained arithmetics
b = (10 + (a * 2)) ** 2

In [79]:
# ELementwise sum
a + b

array([100, 145, 198, 259, 328])

### Comparison Operations

In [80]:
a

array([0, 1, 2, 3, 4])

In [81]:
a >= 2

array([False, False,  True,  True,  True])

In [82]:
b

array([100, 144, 196, 256, 324], dtype=int32)

In [83]:
a > b

array([False, False, False, False, False])

In [84]:
a[a > b]

array([], dtype=int32)

### Summarizing Operations

In [85]:
a.min()

0

In [86]:
a.sum()

10

In [87]:
a.mean()

2.0

In [88]:
a.std()

1.4142135623730951

In [89]:
n.min()

0

### Linear Algebra Refresher

In [91]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [92]:
u + v

array([3, 4, 5, 8])

In [93]:
u * v

array([ 2,  0,  0, 12])

### Vector-Vector Multiplication

In [98]:
# The size of the array
u.shape

(4,)

In [101]:
# First element of the tuple is 4
u.shape[0]

4

In [102]:
v.shape

(4,)

In [103]:
v.shape[0]

4

In [104]:
def vector_vector_multiplication(u, v):
#     Make sure they're of equal sizes for multiplication
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0
    
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [105]:
vector_vector_multiplication(u, v)

14.0

#### Dot product: We already have a function in numpy for the above 

In [107]:
u.dot(v)

14

### Matrix-Vector Multiplication

In [95]:
U = np.array([[2, 4, 5, 6],
             [1, 2, 1, 2],
             [3, 1, 2, 1]])

In [119]:
V = np.array([[1, 1, 2],
              [0, 0.5, 1],
              [0, 2, 1], 
             [2, 1, 0]])

In [109]:
U.shape

(3, 4)

In [110]:
U.shape[0]

3

In [120]:
def matrix_vector_multiplication(U, v):
# In our matrix U, we're interested in the row, multiplying the column of vector v  
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
#     We'll fill it up with zeros for now
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
        
    return result

In [121]:
matrix_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [122]:
# To make use of NUmpy for the above function
U.dot(v)

array([14,  5,  5])

### Matrix Matrix Multiplication

In [129]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
#         Reassigning the zero filled matrix
        result[:, i] = Uvi
        
    return result

In [130]:
matrix_matrix_multiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [131]:
# TO achieve same with numpy
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

### Identity Matrix

In [132]:
I = np.eye(3)

In [133]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [134]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

### Matrix Inverse 

In [136]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [137]:
# TO get the inverse using Linear algebra package
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [138]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])